// Code generated by MockGen. DO NOT EDIT.
// Source: goph-keeper/internal/server/domain/record/repository (interfaces: RecordStore)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/record_store_mock.go -package=mocks goph-keeper/internal/server/domain/record/repository RecordStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "goph-keeper/internal/server/domain/record/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRecordStore is a mock of RecordStore interface.
type MockRecordStore struct {
	ctrl     *gomock.Controller
	recorder *MockRecordStoreMockRecorder
	isgomock struct{}
}

// MockRecordStoreMockRecorder is the mock recorder for MockRecordStore.
type MockRecordStoreMockRecorder struct {
	mock *MockRecordStore
}

// NewMockRecordStore creates a new mock instance.
func NewMockRecordStore(ctrl *gomock.Controller) *MockRecordStore {
	mock := &MockRecordStore{ctrl: ctrl}
	mock.recorder = &MockRecordStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordStore) EXPECT() *MockRecordStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRecordStore) Get(ctx context.Context, ownerID, recordID string) (*model.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ownerID, recordID)
	ret0, _ := ret[0].(*model.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecordStoreMockRecorder) Get(ctx, ownerID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecordStore)(nil).Get), ctx, ownerID, recordID)
}

// ListSince mocks base method.
func (m *MockRecordStore) ListSince(ctx context.Context, ownerID string, sinceVersion int64) ([]*model.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSince", ctx, ownerID, sinceVersion)
	ret0, _ := ret[0].([]*model.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSince indicates an expected call of ListSince.
func (mr *MockRecordStoreMockRecorder) ListSince(ctx, ownerID, sinceVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSince", reflect.TypeOf((*MockRecordStore)(nil).ListSince), ctx, ownerID, sinceVersion)
}

// Update mocks base method.
func (m *MockRecordStore) Update(ctx context.Context, ownerID string, r *model.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ownerID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecordStoreMockRecorder) Update(ctx, ownerID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordStore)(nil).Update), ctx, ownerID, r)
}

// UpdateBatch mocks base method.
func (m *MockRecordStore) UpdateBatch(ctx context.Context, ownerID string, records []*model.Record) ([]*model.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatch", ctx, ownerID, records)
	ret0, _ := ret[0].([]*model.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBatch indicates an expected call of UpdateBatch.
func (mr *MockRecordStoreMockRecorder) UpdateBatch(ctx, ownerID, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatch", reflect.TypeOf((*MockRecordStore)(nil).UpdateBatch), ctx, ownerID, records)
}
