// Code generated by MockGen. DO NOT EDIT.
// Source: goph-keeper/internal/server/domain/session/repository (interfaces: SessionStore)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/session_store_mock.go -package=mocks goph-keeper/internal/server/domain/session/repository SessionStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "goph-keeper/internal/server/domain/session/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionStore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStore)(nil).Delete), ctx, id)
}

// FindActiveByRefreshToken mocks base method.
func (m *MockSessionStore) FindActiveByRefreshToken(ctx context.Context, refreshToken string, now time.Time) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByRefreshToken", ctx, refreshToken, now)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByRefreshToken indicates an expected call of FindActiveByRefreshToken.
func (mr *MockSessionStoreMockRecorder) FindActiveByRefreshToken(ctx, refreshToken, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByRefreshToken", reflect.TypeOf((*MockSessionStore)(nil).FindActiveByRefreshToken), ctx, refreshToken, now)
}

// Get mocks base method.
func (m *MockSessionStore) Get(ctx context.Context, id string) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionStore)(nil).Get), ctx, id)
}

// Rotate mocks base method.
func (m *MockSessionStore) Rotate(ctx context.Context, oldSessionID string, newSession *model.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, oldSessionID, newSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockSessionStoreMockRecorder) Rotate(ctx, oldSessionID, newSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockSessionStore)(nil).Rotate), ctx, oldSessionID, newSession)
}

// Save mocks base method.
func (m *MockSessionStore) Save(ctx context.Context, session *model.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionStoreMockRecorder) Save(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionStore)(nil).Save), ctx, session)
}
