// Code generated by MockGen. DO NOT EDIT.
// Source: goph-keeper/internal/server/domain/user/repository (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/user_repository_mock.go -package=mocks goph-keeper/internal/server/domain/user/repository UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "goph-keeper/internal/server/domain/user/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByLogin mocks base method.
func (m *MockUserRepository) GetByLogin(ctx context.Context, login string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUserRepositoryMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUserRepository)(nil).GetByLogin), ctx, login)
}

// Save mocks base method.
func (m *MockUserRepository) Save(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepository)(nil).Save), ctx, user)
}

// SetMasterSalt mocks base method.
func (m *MockUserRepository) SetMasterSalt(ctx context.Context, userID, masterSalt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasterSalt", ctx, userID, masterSalt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMasterSalt indicates an expected call of SetMasterSalt.
func (mr *MockUserRepositoryMockRecorder) SetMasterSalt(ctx, userID, masterSalt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterSalt", reflect.TypeOf((*MockUserRepository)(nil).SetMasterSalt), ctx, userID, masterSalt)
}
