// Code generated by MockGen. DO NOT EDIT.
// Source: goph-keeper/internal/server/domain/user/repository (interfaces: UserStore)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/user_store_mock.go -package=mocks goph-keeper/internal/server/domain/user/repository UserStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "goph-keeper/internal/server/domain/user/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// GetByLogin mocks base method.
func (m *MockUserStore) GetByLogin(ctx context.Context, login string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUserStoreMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUserStore)(nil).GetByLogin), ctx, login)
}

// Save mocks base method.
func (m *MockUserStore) Save(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserStoreMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserStore)(nil).Save), ctx, user)
}

// SetMasterSalt mocks base method.
func (m *MockUserStore) SetMasterSalt(ctx context.Context, userID, masterSalt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasterSalt", ctx, userID, masterSalt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMasterSalt indicates an expected call of SetMasterSalt.
func (mr *MockUserStoreMockRecorder) SetMasterSalt(ctx, userID, masterSalt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterSalt", reflect.TypeOf((*MockUserStore)(nil).SetMasterSalt), ctx, userID, masterSalt)
}
