// Code generated by MockGen. DO NOT EDIT.
// Source: goph-keeper/internal/domain/record/repository (interfaces: RecordRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/record_repository_mock.go -package=mocks goph-keeper/internal/domain/record/repository RecordRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "goph-keeper/internal/domain/record/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRecordRepository is a mock of RecordRepository interface.
type MockRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordRepositoryMockRecorder is the mock recorder for MockRecordRepository.
type MockRecordRepositoryMockRecorder struct {
	mock *MockRecordRepository
}

// NewMockRecordRepository creates a new mock instance.
func NewMockRecordRepository(ctrl *gomock.Controller) *MockRecordRepository {
	mock := &MockRecordRepository{ctrl: ctrl}
	mock.recorder = &MockRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepository) EXPECT() *MockRecordRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRecordRepository) Get(ctx context.Context, ownerID, recordID string) (*model.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ownerID, recordID)
	ret0, _ := ret[0].(*model.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecordRepositoryMockRecorder) Get(ctx, ownerID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecordRepository)(nil).Get), ctx, ownerID, recordID)
}

// Update mocks base method.
func (m *MockRecordRepository) Update(ctx context.Context, ownerID string, r *model.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ownerID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecordRepositoryMockRecorder) Update(ctx, ownerID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordRepository)(nil).Update), ctx, ownerID, r)
}
